Hides nav bars that shouldn't be visible
subvisual/blog pull request #1
Opened 2017-04-04 13:42 UTC by luisptorres

When pressing the tab key, it was selecting non-visible bars, because although they weren't visible they were selectable. Animations are working as before.

2017-07-06 13:06 UTC, fribmendes commented
@naps62 @pfac can one of you take this?

2017-07-06 14:33 UTC, naps62 commented
To be honest I probably forgot about this PR at the time. shame on me. sorry @luisptorres 

While I understand the issue, I can't accept this as is because using `display: none` breaks the navbar animation. The correct way to fix this would be to programatically add `display: none` via JS after the animation is triggered, and remove it before re-showing the navbar.

Or, alternatively, I don't know if we can do this in any other way, such as using aria labels

2018-01-24 11:25 UTC, pfac requested changes
See @naps62 comment on the broken animation.

2019-01-07 22:24 UTC, naps62 commented
@luistorres so... I guess we're no longer worried about this?

2019-01-08 10:42 UTC, luistorres commented
I though you had deleted the blog. Do you still want me to fix this? @naps62

2019-01-08 14:39 UTC, pfac commented
I'm closing this since nobody knows what the hell this fixes anyway, or if it is relevant at all.

2019-01-08 14:39 UTC, closed without merging